// Mock code generated by mockito package.
// DO NOT EDIT MANUALLY.

// ignore_for_file: non_constant_identifier_names
// ignore_for_file: unnecessary_brace_in_string_interps
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_string_escapes
// ignore_for_file: unnecessary_string_interpolations
// ignore_for_file: unnecessary_this

import 'dart:io' as _i2;

import 'package:mockito/mockito.dart' as _i1;

// ignore: must_be_immutable
class MockDirectory extends _i1.Mock implements _i2.Directory {
  MockDirectory() {
    _i1.throwOnMissingStub(this);
  }
}

// ignore: must_be_immutable
class MockFile extends _i1.Mock implements _i2.File {
  MockFile() {
    _i1.throwOnMissingStub(this);
  }
}